### ISSUE TITLE
Add feature to dataset browser that filters on type of dataset: archive/object collection/publications

### ISSUE THREAD

**Issue by GertjanFi** [colonial-heritage/dataset-browser#59] opened 2023-02-07 13:52 UTC
Through workshop 3-Feb:
Cindy - beschrijving datasets ook selecteren op type dataset archief / collectie ibjecten/publicaties

**Comment by sdevalk** [comment] 2023-03-23 08:26
Duplicate of https://github.com/orgs/colonial-heritage/projects/1?pane=issue&itemId=22567240 ?

**Comment by sdevalk** [comment] 2023-03-30 05:49
The groundwork for this feature is in [this branch](https://github.com/colonial-heritage/dataset-browser/pull/167). We still need to decide on how to model this type of information (i.e. "collection types"), preferably a property from [Schema.org](https://schema.org/Dataset).

**Comment by sdevalk** [comment] 2023-03-30 06:02
About the modeling:
1. We could use Schema.org's [genre](https://schema.org/genre) property ("A dataset is of a certain genre") or [additionalType](https://schema.org/additionalType) ("A dataset is of a certain type", e.g. "A dataset of archival documents")
1. We could borrow properties from DCAT, e.g. "[Classifying dataset types](https://www.w3.org/TR/vocab-dcat-2/#classifying-dataset-types)"

**Comment by sdevalk** [comment] 2023-03-30 06:10
About the terminology source:

1. We could use terms from the AAT's ['document genres' list](https://www.getty.edu/vow/AATHierarchy?find=publication&logic=AND&note=&page=1&subjectid=300026031)
2. We could use terms from LoC's ['genre terms' list](https://id.loc.gov/search/?q=cs:http://id.loc.gov/vocabulary/marcgt&q=memberOf:http://id.loc.gov/vocabulary/marcgt/collection_marcgt)

**Closed** 2023-04-05 08:27 UTC
Labels: Needed for Delivery
